version: '3'

services: 
  app: 
    image: docker-nextjs-dev
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./hooks:/app/hooks
      - ./components:/app/components
      - ./constants:/app/constants
      - ./sdk:/app/sdk



